---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.0
    chart: argo-cd
    helm:
      values: |-
        fullnameOverride: "argo-cd"
        global:
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
        controller:
          containerSecurityContext:
            allowPrivilegeEscalation: false
          replica: 1
        dex:
          containerSecurityContext:
            allowPrivilegeEscalation: false
        redis:
          containerSecurityContext:
            allowPrivilegeEscalation: false
        repoServer:
          replicas: 1
          containerSecurityContext:
            allowPrivilegeEscalation: false
          serviceAccount:
            automountServiceAccountToken: true
            annotations:
              eks.amazonaws.com/role-arn: "{{ .Values.argoCd.kmsArn }}"
          env:
            - name: HELM_PLUGINS
              value: /custom-tools/helm-plugins/
            - name: HELM_SECRETS_HELM_PATH
              value: /usr/local/bin/helm
            - name: HELM_SECRETS_SOPS_PATH
              value: /custom-tools/sops
            - name: HELM_SECRETS_KUBECTL_PATH
              value: /custom-tools/kubectl
          volumes:
            - name: custom-tools
              emptyDir: {}
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
          initContainers:
            - name: download-tools
              securityContext:
                allowPrivilegeEscalation: false
              image: alpine:latest
              command: [sh, -ec]
              args:
                - |
                  mkdir -p /custom-tools/helm-plugins
                  wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v4.2.2/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

                  wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux
                  wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl

                  chmod +x /custom-tools/*
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
        server:
          replicas: 1
          containerSecurityContext:
            allowPrivilegeEscalation: false
          certificate:
            enabled: true
            domain: argocd.{{ .Values.mainDomain }}
            issuer:
              kind: ClusterIssuer
              name: letsencrypt
            additionalHosts: []
            secretName: argocd-server-tls
          ingress:
            enabled: true
            hostname: argocd.{{ .Values.mainDomain }}
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            tls: true
            extraTls:
              - secretName: argocd-ingress-tls
                hosts:
                  - argocd.{{ .Values.mainDomain }}
          config:
            accounts.image-updater: apiKey
            accounts.github-runner: login
            helm.valuesFileSchemes:  secrets, https, http
            url: https://argocd.{{ .Values.mainDomain }}

        configs:
          credentialTemplates:
            argo-apps-creds:
              url: https://github.com/lukas-pastva/kt-eks-gitops
              username: lukas.pastva
              password: "{{ .Values.gitToken }}"


  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true