---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.0.3
    chart: external-dns
    helm:
      values: |-
        provider: aws
        txtPrefix: "ext-dns-"
        txtOwnerId: {{ .Values.fullName }}
        logFormat: json
        policy: sync
        serviceAccount:
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountId }}:role/kt-ops-eks-1-external-dns
        serviceMonitor:
          enabled: true
        txtPrefix: "{{ .Values.fullName }}-"
        txtOwnerId: "{{ .Values.fullName }}-"
        extraArgs:
        {{- range $index, $value := .Values.domainFilter }}
          domain-filter: "{{ $value }}"
        {{- end }}
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
        podSecurityContext:
          fsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi

  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true