---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.4.12
    chart: metrics-server
    helm:
      values: |-
        apiService:
          create: true
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true